Fix race where loadbalancer.available is not cleared early enough
juju-solutions/interface-public-address pull request #4
Opened 2019-02-05 17:13 UTC by Cynerva

This fixes an error observed in CI. While removing a kubernetes-master unit, the `loadbalancer-relation-departed` hook blew up:

```
unit-kubernetes-master-0: 02:17:16 INFO unit.kubernetes-master/0.juju-log loadbalancer:2: Reactive main running for hook loadbalancer-relation-departed
...
unit-kubernetes-master-0: 02:17:21 INFO unit.kubernetes-master/0.juju-log loadbalancer:2: Invoking reactive handler: reactive/kubernetes_master.py:959:loadbalancer_kubeconfig
unit-kubernetes-master-0: 02:17:21 ERROR unit.kubernetes-master/0.juju-log loadbalancer:2: Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kubernetes-master-0/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-kubernetes-master-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-kubernetes-master-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-kubernetes-master-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-kubernetes-master-0/charm/reactive/kubernetes_master.py", line 965, in loadbalancer_kubeconfig
    address = hosts[0].get('public-address')
IndexError: list index out of range
```

The [loadbalancer_kubeconfig](https://github.com/juju-solutions/kubernetes/blob/d71f27ff3a247c3a41b9e09ef96cf333f7cb0cff/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L961) handler ran because `loadbalancer.available` was still set, even though the loadbalancer relation had no joined units. The `loadbalancer.available` flag wasn't cleared because [PublicAddressRequires.broken](https://github.com/juju-solutions/interface-public-address/blob/d09e1e50389a1230383830bb8727d9d6a0991938/requires.py#L18) had not run yet.

This bug was introduced by https://github.com/juju-solutions/interface-public-address/pull/3 when we switched from RelationBase to Endpoint, and in particular, switched from using a `@hook` handler to a `@when_not` handler to clear the `loadbalancer.available` flag.

This PR fixes it by reverting to a `@hook` handler for clearing the flag, which is guaranteed to run before `@when` handlers.

2019-02-05 17:15 UTC, Cynerva commented
@johnsca can you review this?

@battlemidget FYI, this is for the CI failure you saw on 1.14.

2019-02-06 02:28 UTC, johnsca requested changes
I really don't like the idea of moving back to `@hook` and I think that triggers are a better solution for this type of issue.  However, triggers don't currently support watching for clear events, nor a way to register triggers for automatically managed endpoint flags, so I created https://github.com/juju-solutions/charms.reactive/pull/205 to address that.  If we can get that merged and released quickly, this PR can be changed to:

```python
class PublicAddressRequires(Endpoint):
    def register_triggers(self):
        register_trigger(when_not=self.expand_name('endpoint.{endpoint_name}.joined'),
                         clear_flag=self.expand_name('{endpoint_name}.available'))
```

2019-02-06 16:42 UTC, johnsca commented
charms.reactive 1.2.0 is released with this change.

2019-02-06 20:43 UTC, Cynerva commented
Updated and tested, ready for another review.

2019-02-06 21:24 UTC, johnsca approved these changes

2019-02-06 21:24 UTC, merged